name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ shrutikaaak }}
          password: ${{ shruti111 }}

      - name: Build Docker image
        run: |
          docker build -t yourdockerhubusername/yourapp:latest .

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'yourdockerhubusername/yourapp:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true

      - name: Push Docker image
        run: |
          docker push yourdockerhubusername/yourapp:latest
